-- Migration: Create users, qr_codes, and attendance tables
-- Executed at: 2026-06-06T00:30:47Z
-- Generated by Could Code

-- Create roles enum
CREATE TYPE user_role AS ENUM ('admin', 'supervisor', 'employee');

-- Create scan types enum
CREATE TYPE scan_type AS ENUM ('check_in', 'check_out');

-- Create attendance status enum
CREATE TYPE attendance_status AS ENUM ('present', 'late', 'absent', 'departed');

-- Create users table extending auth.users
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    employee_code TEXT UNIQUE NOT NULL,
    department TEXT,
    role user_role DEFAULT 'employee',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create qr_codes table
CREATE TABLE public.qr_codes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    qr_data TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on qr_codes
ALTER TABLE public.qr_codes ENABLE ROW LEVEL SECURITY;

-- Create attendance table
CREATE TABLE public.attendance (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    scanned_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    scan_time TIMESTAMPTZ DEFAULT NOW(),
    status attendance_status NOT NULL,
    scan_type scan_type NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on attendance
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

-- Basic Policies

-- Profiles: Anyone authenticated can read profiles (for supervisors to see employees)
CREATE POLICY "Authenticated users can read profiles" ON public.profiles
    FOR SELECT TO authenticated USING (true);

-- Profiles: Only admins can insert/update/delete
CREATE POLICY "Admins can manage profiles" ON public.profiles
    FOR ALL TO authenticated USING (
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
    );

-- QR Codes: Users can see their own, admins/supervisors can see all
CREATE POLICY "Users can view own QR, Admins/Supervisors view all" ON public.qr_codes
    FOR SELECT TO authenticated USING (
        user_id = auth.uid() OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'supervisor')
    );

-- QR Codes: Admins can manage
CREATE POLICY "Admins can manage QR codes" ON public.qr_codes
    FOR ALL TO authenticated USING (
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
    );

-- Attendance: Users can see their own, admins/supervisors can see all
CREATE POLICY "Users can view own attendance, Admins/Supervisors view all" ON public.attendance
    FOR SELECT TO authenticated USING (
        user_id = auth.uid() OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'supervisor')
    );

-- Attendance: Admins and Supervisors can insert
CREATE POLICY "Admins and Supervisors can insert attendance" ON public.attendance
    FOR INSERT TO authenticated WITH CHECK (
        (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'supervisor')
    );
